services:
  web-backend: 
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
    container_name: web_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ./docs/scripts/startup.sh
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketdata
    volumes:
      - pgdata:.var/lib/postgresql/data
  
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
 pgdata:
  